### ISSUE TITLE
Example Frontend Form Markup error : /question -> /entry

### ISSUE THREAD

**Issue by wdebusschere** [twiro/anti_spam_question#1]
Example Frontend Form Markup:

> <label>

	<xsl:value-of select="//anti-spam-question/question" />
	<input name="anti-spam-question[answer]" type="text" />
	<input name="anti-spam-question[id]" type="hidden" value="{//anti-spam-question/question/@id}" />
</label>

> <label>

	<xsl:value-of select="//anti-spam-question/entry" />
	<input name="anti-spam-question[answer]" type="text" />
	<input name="anti-spam-question[id]" type="hidden" value="{//anti-spam-question/entry/@id}" />
</label>

**Comment by twiro** [comment]
Thank you mate - must have changed this during the refactoring process and forgot to double-check the documentation. Fixed in [2.1.1](https://github.com/twiro/anti_spam_question/tree/2.1.1)!
