### ISSUE TITLE
Parse error on install

### ISSUE THREAD

**Issue by RepublicOfDave** [twiro/anti_spam_question#2]
Hello, was hoping you could help me solve an issue i'm having with the extension...

I'm using Symphony 2.6.11, when I attempt to install the extension the following error displays preventing me from doing so.

**Parse error:** syntax error, unexpected '.', expecting ',' or ';' in **/public_html/extensions/anti_spam_question/lib/class.anti_spam_question.php** on line **27**

Any help would be great,
Many thanks

**Comment by twiro** [comment]
Hey Dave - I will have a look asap!
Could you tell me which PHP version you're using the extension with?

**Comment by RepublicOfDave** [comment]
Thanks for the response twiro, i'm using PHP version 5.4.17.

**Comment by twiro** [comment]
> _i'm using PHP version 5.4.17._

I only tested 5.6 and 5.5 since having refactored the extension, so that must be the cause - could you give the current [integration-branch](https://github.com/twiro/anti_spam_question/tree/integration) a try? I implemented a fix that _should_ work, but I couldn't actually test it...

**Comment by RepublicOfDave** [comment]
That worked a treat, thanks very much twiro!

I just tried to to install it on another Symphony install of mine (Symphony 2.6.4 also using PHP 5.4), no problems enabling, creating the questions or adding it to the event however once I attached the Anti Span Question Data Source to the page the following error displays:

Symphony Fatal Error: Call to a member function getName() on a non-object
An error occurred in /public_html/extensions/multilingual/extension.driver.php around line 312

Seems to conflict with the Multilingual extension (v1.1.0).

Any help with this would be great but I completely understand if you don't want to delve into it conflicting with other extensions.

Many thanks.

**Comment by twiro** [comment]
> _That worked a treat, thanks very much twiro!_

Great to hear - glad I could help :)

> _Any help with this would be great but I completely understand if you don't want to delve into it conflicting with other extensions._

As I just recently adopted the multilingual extension (and currently working on version **[2.0.0](https://github.com/twiro/multilingual/issues/14)** which I plan to release soon) I'm defintively willing to help with solving the conflict.

I just submitted a bugfix-branch **[(1.2.1)](https://github.com/twiro/multilingual/tree/1.2.1)** for [PHP 5.3](https://github.com/twiro/multilingual/issues/16) yesterday and testing this with the latest integration-branch of **anti spam question** works for me with Symphony 2.6.4 _(which just by chance happens to be the Symphony-version I'm currently developing the multilingual extension in)_. I could only test with PHP 5.6 at the moment, but I got the same error you had when switching back to multilingual 1.1.0 - using 1.2.1 it dissapeared!

Could you update the multilingual extension to 1.2.1 and tell me if that works?
If yes I will push 1.2.1 to master branch and release this as the official stable version.

**Comment by RepublicOfDave** [comment]
> Could you update the multilingual extension to 1.2.1 and tell me if that works?

Done and working great now!

Thank you for all your help in getting these issues sorted twiro, so great to have this extension working as it really is a keeper.

Thanks again.

**Comment by twiro** [comment]
> _Done and working great now!_

Great! So I will push the fix to master right now...

> _Thank you for all your help in getting these issues sorted twiro, so great to have this extension working as it really is a keeper._

My pleasure :) And you caught a good moment as I'm pretty involved testing/developing these extensions anyway, so it was easy to react quicker than I normally could have done - glad it works now and glad you find it useful!

And if it's a keeper you're very welcome to "star" the repo ;) _(Always helps a repo making a good "first impression" to new adopters)_
