### ISSUE TITLE
PHP 7 : Datasource Error

### ISSUE THREAD

**Issue by wdebusschere** [twiro/anti_spam_question#4]
Line 24 data.anti_spam_question.php

`public function execute(&$param_pool=NULL) {`

to

`public function execute(array &$param_pool=NULL) {`

**Comment by twiro** [comment]
I'm currently testing PHP7-support for this extension - do you use it in production with PHP7 and is everything else working as expected for you?

**Comment by twiro** [comment]
PHP7 support should be fixed in the latest release:

https://github.com/twiro/anti_spam_question/releases/tag/2.2.0
